name: ci

on:
  push:
    branches: [main]
  pull_request:

jobs:
  setup:
    runs-on: ubuntu-latest
    outputs:
      bun-cache-key: ${{ steps.cache-key.outputs.key }}
    steps:
      - uses: actions/checkout@v4

      - name: Setup Bun
        uses: oven-sh/setup-bun@v1


      - name: Cache bun deps
        id: cache-key
        run: echo "key=bun-${{ hashFiles('bun.lockb') }}" >> "$GITHUB_OUTPUT"

      - uses: actions/cache@v4
        with:
          path: ~/.bun/install/cache
          key: ${{ steps.cache-key.outputs.key }}

      - run: bun install --frozen-lockfile

      - run: bunx tsc --noEmit

  biome-check:
    needs: setup
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: oven-sh/setup-bun@v1
      - run: bun install --frozen-lockfile

      - name: Biome CI check
        run: bunx biome ci .

  lint:
    needs: setup
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: oven-sh/setup-bun@v1
      - run: bun install --frozen-lockfile

      - run: bunx biome lint .

  test:
    needs: [biome-check, lint]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: oven-sh/setup-bun@v1
      - run: bun install --frozen-lockfile

      - run: bun test

  build:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: oven-sh/setup-bun@v1
      - run: bun install --frozen-lockfile

      - run: bun run build
